/*sf::CircleShape circle(50.f);
	circle.setFillColor(sf::Color(230, 0, 230));
	circle.setOutlineThickness(15.f);
	circle.setOutlineColor(sf::Color(80, 220, 50, 0));
	circle.move(5, 10);
	window.draw(circle);
	sf::CircleShape triangle(65.f, 3);
	triangle.setPosition(125, 10);
	triangle.setFillColor(sf::Color::Blue);
	window.draw(triangle);
	sf::CircleShape square(60.f, 4);
	square.setPosition(250, 10);
	square.setFillColor(sf::Color::Red);
	window.draw(square);
	sf::CircleShape octagon(60.f, 8);
	octagon.setPosition(380, 10);
	octagon.setFillColor(sf::Color::Cyan);
	window.draw(octagon);
	sf::ConvexShape convex;
	convex.setPointCount(5);
	convex.setPoint(0, sf::Vector2f(0.f, 0.f));
	convex.setPoint(1, sf::Vector2f(150.f, 10.f));
	convex.setPoint(2, sf::Vector2f(120.f, 90.f));
	convex.setPoint(3, sf::Vector2f(30.f, 100.f));
	convex.setPoint(4, sf::Vector2f(5.f, 50.f));
	convex.setFillColor(sf::Color::Black);
	convex.move(1, 150);
	window.draw(convex);
	sf::RectangleShape rectangle(sf::Vector2f(70.f, 100.f));
	rectangle.move(165, 150);
	rectangle.setFillColor(sf::Color(175, 120, 0));
	window.draw(rectangle);
	sf::RectangleShape line_1(sf::Vector2f(130.f, 5.f));
	line_1.rotate(45.f);
	line_1.setFillColor(sf::Color(15, 150, 140));
	line_1.move(250, 150);
	window.draw(line_1);
	sf::Vertex line_2[] = {
		sf::Vertex(sf::Vector2f(390.f, 240.f)),
		sf::Vertex(sf::Vector2f(470.f, 150.f)),
	};
	line_2->color = sf::Color::Black;
	window.draw(line_2, 2, sf::Lines);*/
	/*sf::Texture texture;
	texture.loadFromFile("texture.png");
	texture.setSmooth(true);
	sf::Sprite sprite_1(texture);
	sf::Sprite sprite_2(texture);
	sf::Sprite sprite_3(texture);
	sf::Sprite sprite_4(texture);
	sf::Sprite sprite_5(texture);
	sf::Sprite sprite_6(texture);
	sf::Sprite sprite_7(texture);
	sprite_2.move(105, 0);
	sprite_2.setColor(sf::Color::Green);
	sprite_3.move(210, 0);
	sprite_3.setColor(sf::Color::Red);
	sprite_4.move(315, 0);
	sprite_4.setColor(sf::Color::Yellow);
	sprite_5.move(420, 0);
	sprite_5.setColor(sf::Color(255, 255, 255, 128));
	sprite_6.move(525, 0);
	sprite_6.setColor(sf::Color(255, 255, 255, 64));
	sprite_7.move(630, 0);
	sprite_7.setColor(sf::Color(255, 255, 255, 23));
	window.draw(sprite_1);
	window.draw(sprite_2);
	window.draw(sprite_3);
	window.draw(sprite_4);
	window.draw(sprite_5);
	window.draw(sprite_6);
	window.draw(sprite_7);
	window.display();*/